### PR TITLE
Made navigation to create ad page, to registration. Implement same fo…

### PR DESCRIPTION
**Pull request by gintunas**
…rm styles and navigation functionality with buttons.

### CODE REVIEW

**Review by MellowJay — COMMENTED** [review]
Basically, this error popped up and I found that it has to do something with special characters and then I remembered that Gintautas mentioned comments being a problem in these files. I found all menuitem instances in the navbar file and found that the first TODO comment was yellow in color. I moved both comments to the start of the file and everything worked. I uploaded the error screen for reference and the full message.

[err.txt](https://github.com/Pyragas/tool-rent/files/6430682/err.txt)

s

**Review by MellowJay — CHANGES_REQUESTED** [review]
I tested some of the paths for pages and some of them don't work.
I'll list the ones that I found aren't working:
  Create Advertisement -> Home
  Create Advertisement -> MyProfile
  Create Advertisement -> Search Advertisements
  Create Advertisement -> Login
  Search Advertisements -> Home
  Register/Login -> Home
  Example Item -> Home

After registering it brings up the main page and then if you go to another page and then go back it asks you to register again. I uploaded pictures. After registering you see index page, but its actually the register page url for some reason.

image

**Review by MellowJay — CHANGES_REQUESTED** [review]
Okay, so from my testing the only page paths that are missing are for the Create Advertisement page.

**Comment by gintunas** [comment]
I am fixing the paths, remade the navbar and single page layout file, so we won't need to include navbar in every page. So probably we'll need to test in once again after I will fix everything.

**Comment by gintunas** [comment]
@MellowJay Remade everything. Would be nice if you could perfrom quick tests.

**Review by MellowJay — COMMENTED** [review]
Ok, seems good.

**Review by MellowJay — APPROVED** [review]

**Pull request merged**
